services:
  
  nginx:
    build: ./requirements/nginx
    image: nginx:v1.0
    container_name: nginx
    depends_on:
      - wordpress
    restart: unless-stopped
    ports:
      - '443:443'
    volumes:
      - wp_data:/var/www/html
    networks:
      - my_network

  mariadb:
    build: ./requirements/mariadb
    image: mariadb:v1.0
    container_name:  mariadb
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DB_USER}
    secrets:
      - mb_password
    networks:
      - my_network

  wordpress:
    build: ./requirements/wordpress/
    image: worpdresss:v1.0
    container_name: wordpress
    depends_on:
      - mariadb
      - redis
    restart: unless-stopped
    ports:
      - '9000:9000'
    volumes:
      - wp_data:/var/www/html
    env_file:
      - .env
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_NAME=${DATABASE_NAME}
      - WORDPRESS_DB_USER=${DB_USER}
    secrets:
      - mb_password
      - wp_password
      - wp_admin_password
    networks:
      - my_network
  
  adminer:
    build: ./requirements/bonus/adminer
    image: adminer:v1.0
    container_name: adminer
    depends_on:
      - mariadb
    restart: unless-stopped
    ports:
      - '4242:8080'
    networks:
      - my_network
    
  ftp:
    build: ./requirements/bonus/FTPserver
    image: ftp:v1.0
    container_name: ftp
    restart: unless-stopped
    ports:
      - '21:21'
      - '21100-21110:21100-21110'
    volumes:
      - wp_data:/var/www/html
    env_file:
      - .env
    secrets:
      - ftp_password
    networks:
      - my_network

  redis:
    build: ./requirements/bonus/redis-cache
    image: redis-cache:v1.0
    container_name: redis-cache
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - my_network

  rsync:
    build: ./requirements/bonus/rsync
    image: rsync:v1.0
    container_name: rsync
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DB_USER}
    volumes:
      - wp_data:/var/www/html
      - rsync_data:/home/backup
    secrets:
      - mb_password
    networks:
      - my_network

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/cbauer/data/mariadb
  
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/cbauer/data/wordpress

  rsync_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/cbauer/data/rsync

networks:
  my_network:
    driver: bridge

secrets:
  mb_password:
    file: ../secrets/mb_password.txt
  wp_password:
    file: ../secrets/wp_password.txt
  ftp_password:
    file: ../secrets/ftp_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt