services:
  
  nginx:
    build: ./requirements/nginx
    image: nginx:v1.0
    container_name: nginx
    depends_on:
      - wordpress # fuer connectgion port 9000
    restart: unless-stopped
    ports:
      - '443:443'
    volumes:
      # - ../secrets:/etc/letsencrypt
      - wp_data:/var/www/html #geben location von volumes an nginx weiter
    networks:
      - my_network

  mariadb:
    build: ./requirements/mariadb
    image: mariadb:v1.0
    container_name:  mariadb
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      - my_network

  wordpress:
    build: ./requirements/wordpress/
    image: worpdresss:v1.0
    container_name: wordpress
    depends_on:
      - mariadb
      - redis
    restart: unless-stopped
    ports:
      - '9000:9000'
    volumes:
      - wp_data:/var/www/html
    env_file:
      - .env
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_NAME=${DATABASE_NAME}
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
    networks:
      - my_network
  
  adminer:
    build: ./requirements/bonus/adminer
    image: adminer:v1.0
    container_name: adminer
    depends_on:
      - mariadb
    restart: unless-stopped
    ports:
      - '4242:8080'
    networks:
      - my_network
    
  ftp:
    build: ./requirements/bonus/FTPserver
    image: ftp:v1.0
    container_name: ftp
    restart: unless-stopped
    ports:
      - '21:21'
      - '21100-21110:21100-21110'
    volumes:
      - wp_data:/var/www/html
    env_file:
      - .env
    networks:
      - my_network

  static-website:
    build: ./requirements/bonus/staticWebsite
    image: static-website:v1.0
    container_name: static-site
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - my_network

  redis:
    build: ./requirements/bonus/redis-cache
    image: redis-cache:v1.0
    container_name: redis-cache
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - my_network

  # portaniner:
  #   build: ./requirements/bonus/portainer
  #   image: portainer:v1.0
  #   container_name: portainer
  #   restart: unless-stopped
  #   ports:
  #     - ""
  #   networks:
  #     -my_network

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/cbauer/data/mariadb
  
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/cbauer/data/wordpress

networks:
  my_network:
    driver: bridge


# falls nicht funktioniert fix ist image names
# wenn ich den die website machen will, die static website, dann muss ich einen weiteren port in der nginx.conf  aufmachen oder ? einfach eine neue location dann?