services:
  
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress # fuer connectgion port 9000
    restart: unless-stopped
    ports:
      - '443:443'
    volumes:
      # - ../secrets:/etc/letsencrypt
      - wp_data:/var/www/html #geben location von volumes an nginx weiter
    networks:
      - my_network

  mariadb:
    build: ./requirements/mariadb
    container_name:  mariadb
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      - my_network

  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    depends_on:
      - mariadb
    #brauche ich ein depends on?
    restart: unless-stopped
    volumes:
      - wp_data:/var/www/html
    env_file:
      - .env
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_NAME=${DATABASE_NAME}
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
      #- WORDPRESS_DB_NAME=wordpress
    networks:
      - my_network
  
  # adminer:
  #   build: ./requirements/bonus/adminer
  #   container_name: adminer
  #   depends_on:
  #     - maraidb
  #   restart: unless-stopped
  #   ports:
  #     - '8080:8080'
  #   networks:
  #     - my_network
    
volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/cbauer/data/mariadb
  
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/cbauer/data/wordpress

networks:
  my_network:
    driver: bridge
