events {
    worker_connections 1024;
}
# PHP-FMP proxy to WordPress container


http
{
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always; # HSTS Header (HTTP Strict Transport Security) - zwingt Browser, nur über HTTPS zu kommunizieren
    
    server {
        listen 443 ssl;
        server_name cbauer.42.fr; 

        # Certificates
        ssl_certificate /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;

        # Nur TLS v1.3 ODER 1.2
        ssl_protocols TLSv1.3; 

        # Security: starkeCipher-Suites
        ssl_prefer_server_ciphers on;

        # root zu Wordpress data
        root /var/www/html; # <- volume aus docker-compose.yml
        index index.php index.html;

        # location / {
        #     try_files $uri $uri/ /index.php?$args;
        # }
        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass wordpress:9000; # Container-Name + Port aus docker-compose.yml <- habe ich noch nicht im docker-compose; muss exakt der Service-Name in der compose sein
            # fastgci_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name; ##?????
        }
    }
}